Transformada GameEngine em uma classe abstrata e foi criada uma nova …
rodriggochaves/scala-game-of-life pull request #15
Opened 2017-10-06 12:54 UTC by diogoqds

…classe que herda de GameEngine

2017-10-06 13:13 UTC, rodriggochaves commented on src/main/scala/br/unb/cic/poo/gol/GameEngine.scala
> +  // }
acho que podemos apagar esses comentários

2017-10-06 13:16 UTC, rodriggochaves commented
Então, também acho que podemos colocar essas pastas no `.gitignore`:

`.metadata`

2017-10-06 13:28 UTC, rodriggochaves requested changes
Algumas melhorias no unico commit

2017-10-06 13:28 UTC, rodriggochaves commented on src/main/scala/br/unb/cic/poo/gol/GameEngine.scala
1. Acho que podiamos remover esses comentários do código antigo.
2. Transformar esses dois métodos em abstratos.
3. Adicionar um comentário explicando o que esses dois métodos supostamente devem fazer.

2017-10-06 13:28 UTC, rodriggochaves commented on src/main/scala/br/unb/cic/poo/gol/VerifyCell.scala
> +abstract class VerifyCell{
Qual objetivo dessa classe?

2017-10-06 19:11 UTC, rodriggochaves approved these changes

2017-10-08 15:24 UTC, soutokevin approved these changes

2017-10-08 20:23 UTC, fillypenascimento approved these changes

2017-10-09 20:35 UTC, rodriggochaves commented
@diogoqds, depois que atualizamos a estrutura do projeto, a gente precisa atualizar seu commit via merge. Conto com você!

2017-10-09 20:36 UTC, rodriggochaves requested changes
atualizar com a merge

2017-10-10 15:04 UTC, rodriggochaves approved these changes

2017-10-13 15:16 UTC, merged